import "dotenv/config"
import { defineConfig } from 'prisma/config'

export default defineConfig({
  datasource : {
    url: process.env.DATABASE_URL!,
  },
})





/* // This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});*/

//DATABASE_URL=postgresql://neondb_owner:npg_Tx95HYWXPqjQ@ep-aged-pond-ac2tr05z-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require